obj-$(CONFIG_ASPEED_BMC_MISC) += aspeed-bmc-misc.o
obj-$(CONFIG_AST_VIDEO)		+= ast_video.o
obj-$(CONFIG_ASPEED_JTAG)	+= aspeed-jtag.o
obj-$(CONFIG_ASPEED_MCTP)	+= aspeed-mctp.o
obj-$(CONFIG_ASPEED_XDMA)	+= aspeed-xdma.o
