#
# Makefile for the ASPEED drivers.
#

obj-$(CONFIG_AST_VGAVIDEO)	+= ast_vgavideo.o
obj-$(CONFIG_AST_VIDEO)		+= ast_video.o
obj-$(CONFIG_AST_LPC)		+= ast-lpc.o ast-lpc_plus.o 
obj-$(CONFIG_AST_IPMI_KCS)	+= ast-kcs.o
obj-$(CONFIG_AST_IPMI_BT)	+= ast-bt.o
obj-$(CONFIG_AST_SNOOP)		+= ast-snoop.o
obj-$(CONFIG_AST_SNOOP_DMA)	+= ast-snoop-dma.o
obj-$(CONFIG_ADC_CAT9883)	+= adc_cat9883.o
obj-$(CONFIG_AST_GPIO) 		+= ast_gpio.o
obj-$(CONFIG_AST_PECI)		+= ast_peci.o
obj-$(CONFIG_AST_MBX)		+= ast_mailbox.o
obj-$(CONFIG_AST_JPEG)		+= ast-jpeg.o
obj-$(CONFIG_ASPEED_JTAG)	+= aspeed-jtag.o #ast-g6-jtag.o
obj-$(CONFIG_AST_HID)		+= ast_hid.o
obj-$(CONFIG_ASPEED_MCTP)	+= aspeed-mctp.o #ast_g6_mctp.o
obj-$(CONFIG_ASPEED_XDMA)	+= aspeed-xdma.o #ast_g6_xdma.o
obj-$(CONFIG_ASPEED_ESPI)	+= aspeed-espi.o
obj-$(CONFIG_AST_VHUB)          += ast_vhub.o
obj-$(CONFIG_AST_CRYPTO)	+= ast_crypto.o aes.o
obj-$(CONFIG_AST_H264)		+= ast_h264.o
obj-$(CONFIG_AST_FORMATTER)	+= ast_formatter.o
obj-$(CONFIG_AST_EGFX)		+= ast_egfx.o
obj-$(CONFIG_AST_RLE)		+= ast_rle.o
obj-$(CONFOG_AST_ENTROPY)	+= ast_entropy.o
obj-$(CONFIG_AST_BITBLT)	+= ast_bitblt.o
obj-$(CONFIG_AST_BULK)		+= ast_bulk.o
obj-$(CONFIG_AST_CMDQ)		+= ast_cmdq.o
obj-$(CONFIG_AST_MASK)		+= ast_mask.o

