# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_ASPEED_BMC_MISC)	+= aspeed-bmc-misc.o
obj-$(CONFIG_ASPEED_BMC_DEV)	+= aspeed-bmc-dev.o
obj-$(CONFIG_ASPEED_HOST_BMC)	+= aspeed-host-bmc-dev.o
obj-$(CONFIG_ASPEED_HID)	+= aspeed-hid.o
obj-$(CONFIG_ASPEED_LPC_CTRL)	+= aspeed-lpc-ctrl.o
obj-$(CONFIG_ASPEED_LPC_SNOOP)	+= aspeed-lpc-snoop.o
obj-$(CONFIG_ASPEED_LPC_PCC)	+= aspeed-lpc-pcc.o
obj-$(CONFIG_ASPEED_LPC_MBOX)	+= aspeed-lpc-mbox.o
obj-$(CONFIG_ASPEED_P2A_CTRL)	+= aspeed-p2a-ctrl.o
obj-$(CONFIG_ASPEED_XDMA)	+= aspeed-xdma.o
obj-$(CONFIG_ASPEED_UDMA)	+= aspeed-udma.o
obj-$(CONFIG_ASPEED_VIDEO)	+= ast_video.o
obj-$(CONFIG_ASPEED_ESPI)	+= aspeed-espi.o \
				aspeed-espi-peripheral.o \
				aspeed-espi-vw.o \
				aspeed-espi-flash.o \
				aspeed-espi-oob.o
obj-$(CONFIG_ASPEED_ESPI_MMBI)	+= aspeed-espi-mmbi.o
obj-$(CONFIG_ASPEED_JTAG)	+= aspeed-jtag.o
