/* SPDX-License-Identifier: (GPL-2.0+ OR MIT) */
#ifndef DT_BINDINGS_ASPEED_SCU_IRQ_H
#define DT_BINDINGS_ASPEED_SCU_IRQ_H

#define ASPEED_SCU_VGA_CURSOR_CHANGE		0
#define ASPEED_SCU_VGA_SCRATCH_REG_CHANGE	1
#define ASPEED_SCU_PCIE_REST_LOW_TO_HIGH	2
#define ASPEED_SCU_PCIE_REST_HIGH_TO_LOW	3
#define ASPEED_SCU_LPC_REST_LOW_TO_HIGH		4
#define ASPEED_SCU_LPC_REST_HIGH_TO_LOW		5
#define ASPEED_SCU_ISSUE_MSI			6
#endif
