#!/bin/sh
# Pre-commit hook for running the Linux coding style checker
# Available at:
#  https://github.com/torvalds/linux/blob/master/scripts/checkpatch.pl
#  https://github.com/torvalds/linux/blob/master/scripts/spelling.txt

if [ -f "scripts/checkpatch.pl" ]; then
    CHECKPATCH=scripts/checkpatch.pl
else
    echo "checkpatch.pl not found"
    exit -1
fi

git diff --cached HEAD | $CHECKPATCH --no-tree --no-signoff --summary-file -q

if [ $? != 0 ]; then
    echo "Coding style checked failed.  Please fix warnings and errors and try committing again."
    exit -1
fi

exit 0
