#
# Makefile for the linux kernel.
#

obj-y 			+= timer.o devs.o ast-ahbc.o ast-pciarbiter.o

obj-$(CONFIG_IRMP)	+= ast-bmc-scu.o

obj-$(CONFIG_RT360_CAM) += ast-cam-scu.o

obj-$(CONFIG_ARCH_AST1070) += ast1070-irq.o ast1070-scu.o ast1070-i2c-irq.o dev-ci2c.o dev-cuart.o dev-clpc.o 

ifeq ($(CONFIG_PCI),y)
obj-$(CONFIG_PCIE_AST)	+= ast-p2x.o
endif

obj-$(CONFIG_AST2400_BMC) += ast2400-irq.o ast2400-scu.o dev-ast2400-uart.o #dev-ast2400-i2c.o

#obj-n   := dummy.o
#platform
obj-y			+= dev-uart.o dev-vuart.o dev-wdt.o dev-rtc.o dev-gpio.o dev-sgpio.o dev-crypto.o

#Storage
obj-y 	                += dev-nor.o dev-nand.o dev-sdhci.o

#bus
obj-y                   += dev-i2c.o dev-spi.o dev-ehci.o dev-uhci.o dev-lpc.o dev-espi.o dev-peci.o dev-kcs.o dev-bt.o dev-snoop.o dev-mbx.o dev-pcie.o dev-jtag.o dev-mctp.o dev-xdma.o

#dev
obj-y			+= dev-udc11.o dev-hid.o dev-udc20.o
#net
obj-y			+= dev-eth.o

#hwmon
obj-y                   += dev-pwm-fan.o dev-adc.o

#video
obj-y			+= dev-fb.o dev-video.o dev-h264.o dev-formatter.o dev-rfx.o 

obj-y			+= dev-rng.o
