obj-$(CONFIG_HDMI_CAT66121)	+= cat66121_hdmi.o \
                                        cat66121_hdmi_hw.o \
                                        hdmitx_input.o \
                                        hdmitx_drv.o \
                                        csc.o \
					hdmitx_hdcp.o \
                                        sha1.o

